### ISSUE TITLE
Question: Why use count?

### ISSUE THREAD

**Issue by douglasg14b** [yosraemad/redux-toolkit-tutorial#2]
Brand new to react, long time Vue dev, and I'm puzzled why you are using a `count` property as a separate piece of state to keep in sync when the todo array already has a `length` property that serves the same purpose?

Is it necessary for reactivity, or just an ad-hoc choice? If the former, can you expand on that?

**Comment by yosraemad** [comment]
Hey! You're fine with using the `length` property of the Todo array! For the sake of the tutorial, I added the count property to show that you can use different state types in the state, and I wanted to illustrate how to use them together :) but you're right, the count property is redundant.

**Comment by douglasg14b** [comment]
Thanks for the clarification!
